#!/usr/bin/env python3
"""
Quick manual test of core SocrAItes functionality
"""

import requests
import time

def quick_test():
    print("🔬 Quick SocrAItes Test")
    print("=" * 30)
    
    base_url = "http://localhost:5000"
    
    # Test philosophers endpoint
    try:
        print("1. Testing philosophers endpoint...")
        response = requests.get(f"{base_url}/api/philosophers", timeout=10)
        if response.status_code == 200:
            data = response.json()
            print(f"   ✅ {len(data.get('philosophers', []))} philosophers loaded")
        else:
            print(f"   ❌ Error: {response.status_code}")
    except Exception as e:
        print(f"   ❌ Exception: {e}")
    
    # Test one chat
    try:
        print("\n2. Testing Camus chat...")
        start_time = time.time()
        response = requests.post(
            f"{base_url}/api/chat",
            json={'message': 'What is the absurd?', 'philosopher': 'camus'},
            timeout=30
        )
        end_time = time.time()
        
        if response.status_code == 200:
            data = response.json()
            response_time = end_time - start_time
            print(f"   ✅ Response in {response_time:.2f}s")
            print(f"   📝 Preview: {data.get('response', '')[:100]}...")
            print(f"   🔧 Generated by: {data.get('generated_by', 'unknown')}")
        else:
            print(f"   ❌ Error: {response.status_code}")
            print(f"   📄 Response: {response.text[:200]}")
    except Exception as e:
        print(f"   ❌ Exception: {e}")
    
    print("\n🎯 Manual test in browser at: http://localhost:5000")
    print("   Try asking different philosophers questions!")

if __name__ == "__main__":
    quick_test()