#!/usr/bin/env python3
"""
Quick performance test for SocrAItes chatbot
"""
import requests
import time
import json

def test_chat_performance():
    print("🧪 Testing SocrAItes Chat Performance...")
    print("=" * 50)
    
    # Test different philosophers
    tests = [
        {"message": "What is the meaning of life?", "philosopher": "camus"},
        {"message": "How should we live?", "philosopher": "nietzsche"},
        {"message": "What is suffering?", "philosopher": "dostoevsky"}
    ]
    
    for i, test in enumerate(tests, 1):
        print(f"\n🔬 Test {i}: {test['philosopher'].title()} - '{test['message']}'")
        
        start_time = time.time()
        try:
            response = requests.post(
                'http://localhost:5000/api/chat',
                json=test,
                timeout=30
            )
            end_time = time.time()
            
            response_time = end_time - start_time
            print(f"⏱️  Response time: {response_time:.2f} seconds")
            
            if response.status_code == 200:
                data = response.json()
                print(f"✅ Success!")
                print(f"🤖 Generated by: {data.get('generated_by', 'unknown')}")
                print(f"🧠 System: {data.get('system_type', 'unknown')}")
                print(f"🌐 Internet enabled: {data.get('internet_enabled', False)}")
                print(f"📝 Response preview: {data.get('response', '')[:150]}...")
                
                # Performance assessment
                if response_time < 3:
                    print("🚀 FAST response!")
                elif response_time < 7:
                    print("⚡ Good response time")
                else:
                    print("🐌 SLOW response - needs optimization")
                    
            else:
                print(f"❌ Error: {response.status_code}")
                print(f"Error details: {response.text}")
                
        except requests.exceptions.Timeout:
            print("⏰ TIMEOUT - Response took too long!")
        except Exception as e:
            print(f"❌ Exception: {e}")
    
    print("\n" + "=" * 50)
    print("🏁 Performance test completed!")

if __name__ == "__main__":
    test_chat_performance()